### ISSUE TITLE
urllib.urequest SSL Error ESP-IDF 3.1

### ISSUE THREAD

**Issue by mrwhy-orig** [pfalcon/pycopy-lib#44]
SSL connections are throwing a mbedtls_ssl_handshake error: -0x4290

I'm using the method only for a dataless get request. It is working without ssl.

My SSL certificate on the server side is a properly signed RSA 2048

**Comment by pfalcon** [comment]
Reference platform for pycopy-lib is the latest version of Pycopy, Unix version. All issues should be tested against that it. If you can't reproduce problem with Pycopy Unix port, it means that the problem is not with pycopy-lib, but with your particular port. Note that Pycopy inherits all "baremetal" ports from the upstream MicroPython project, so any issue with such should be reported upstream.
